version: 2.1
orbs:
  node: circleci/node@3.0.0
  pa11yci: nebulab/pa11yci@1.0.0
  lighthouse-check: foo-software/lighthouse-check@0.0.8
executors:
  docker-executor:
      docker:
          - image: circleci/node:latest-browsers
            user: root
jobs:
  lighthouse: 
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.salesforce.com
  a11y: 
    executor: pa11yci/default
    steps:
      - pa11yci/a11y-audit:
          custom_url_command: |
workflows:
  build-and-deploy:
    jobs:
      - a11y
      - lighthouse