version: 2.1
orbs:
  node: circleci/node@3.0.0
  pa11yci: nebulab/pa11yci@1.0.0
workflows:
  build-and-deploy:
    jobs:
      - pa11yci/a11y-audit:
          custom_url_command:  |
              if [[ -f /tmp/workspace/preview-url ]]; then
                sed -i -e "s#https://test.myproject.com#`cat /tmp/workspace/preview-url`#g" .pa11yci
              fi