version: 2.1
orbs:
  node: circleci/node@3.0.0
  pa11yci: nebulab/pa11yci@1.0.0
workflows:
  node-tests:
    jobs:
      - pa11yci/a11y-audit:
          custom_url_command: pally-ci https://www.salesforce.com
          filters:
              branches:
                ignore: master
