version: 2.1
orbs:
  node: circleci/node@3.0.0
  pa11yci: nebulab/pa11yci@1.0.0
workflows:
  build-and-deploy:
    jobs:
      - pa11yci/a11y-audit:
          custom_url_command: pa11y-ci --sitemap http://pa11y.org/sitemap.xml
          filters:
            branches:
              only: master
jobs:
  tests:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec
  deploy:
    docker:
      - image: circleci/ruby
    steps:
      - run:
          name: Deploy to production
          command: git push production master